// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR2YXb6Npl3Bn3AvDL9diu3Wlr4vfV0Sc',
    appId: '1:50671498192:web:7ca163dd0dbcd9109dffd5',
    messagingSenderId: '50671498192',
    projectId: 'studenthub-9ca44',
    authDomain: 'studenthub-9ca44.firebaseapp.com',
    storageBucket: 'studenthub-9ca44.appspot.com',
    measurementId: 'G-L9V80GPDPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvb6CE7UO6FneoDzaw7X3yOaEHBFP3GaQ',
    appId: '1:50671498192:android:6356bac0915c95d89dffd5',
    messagingSenderId: '50671498192',
    projectId: 'studenthub-9ca44',
    storageBucket: 'studenthub-9ca44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxLN5RUbdT2-Fm9XO4I_pKyLmRYYWTFRU',
    appId: '1:50671498192:ios:c3cd4aa3827890b89dffd5',
    messagingSenderId: '50671498192',
    projectId: 'studenthub-9ca44',
    storageBucket: 'studenthub-9ca44.appspot.com',
    iosBundleId: 'com.example.studentHub',
  );
}
